// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqkyftocmrowajhdyopd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxa3lmdG9jbXJvd2FqaGR5b3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjA4NzgsImV4cCI6MjA2NzM5Njg3OH0.raUjsGVNRgaiTj9iWVqFNtINdnSP5Xs2PbyYPpUK01M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});